### ISSUE TITLE
MonetDBe - Create table from another table

### ISSUE THREAD

**Issue by Guillaume789** [MonetDBSolutions/MonetDBe-Java#4] opened 2021-05-03 16:27 UTC
I was able to run below query with MonetDB.

`create table cube_table_1620058905477_2 as (select M_TP_PFOLIO,M_TRN_FMLY,M_TRN_GRP,M_TRN_TYPE,M_INSTRUMENT,NB_RECORDS,DIFF_PC_NF_EUR,DIFF_PC_NF_EUR2,DIFF_MV_NF_EUR,DIFF_PCR_NF_BK from cube_table_1620058905477 where 1=0)
`
Now with MonetDBe, I get an exception.
[hs_err_pid18348.log](https://github.com/MonetDBSolutions/MonetDBe-Java/files/6416146/hs_err_pid18348.log)

Could you please let me know what would be the best way to create a table from another table with MonetDBe ?

Thanks,
Guillaume

**Comment by bernardom29** [comment] 2021-05-04 08:37
Hi Guillaume, happy that you're trying out our new product!

Could you share some more info about the database schema or queries? I tried to replicate this with a (very) simple example and I didn't get an error, so I'd like to try it out with something closer to your use case.
Appreciate the error log, but unfortunately these JNI logs don't give us much information about what is happening on the C level of MonetDBe.

Thanks :)

**Comment by Guillaume789** [comment] 2021-05-04 08:45
Hi,
I will try to provide more information about my test case. In the meantime, I was just wondering if it could be related to the other issue about NULL values ? (as my table contains NULL values).
I will do some more tests and get back to you with a simple case.

Thanks, Guillaume

**Comment by Guillaume789** [comment] 2021-05-06 19:16
Hi,

actually it is very difficult to isolate a specific case.
I can reproduce the crash by executing basic queries from the GUI of my application:

**Example: Crash  (using a GUI application)**
`create table table_test (COL1 STRING)

insert into table_test (COL1) values ('Hello')
insert into table_test (COL1) values ('World')

select count(*) as COUNT_LINES from table_test
--> return value: 2

select COL1 from table_test
--> Crash !
`
[hs_err_pid20044.log](https://github.com/MonetDBSolutions/MonetDBe-Java/files/6437088/hs_err_pid20044.log)

However, if I create a simple test class with the above commands, then it works fine.
Is it due to memory leaks ? to potential conflicts with other jars ?

Thanks,
Guillaume

**Comment by Guillaume789** [comment] 2021-05-13 07:51
Hi,
another test case.

1) From the GUI I run below query:
`select tables.name from tables where tables.system=false`
--> returns empty result

2) If I run the same query a second time, I got a crash
[hs_err_pid144.log](https://github.com/MonetDBSolutions/MonetDBe-Java/files/6471043/hs_err_pid144.log)

Regards,
Guillaume

Note that if I run below query from the GUI, it is crashing even the first time !
`select tables.name from tables`

I do not have the crash when running the above queries without GUI (using java code without swing GUI).

**Comment by Guillaume789** [comment] 2021-05-17 06:07
Hi,

I have used a well known Java SQL client "SQL-Workbench123" to test MonetDBe.

I have defined a new Driver connection for MonetDBe.
If I run below query from the GUI I get a crash!
`select tables.name from tables where tables.system=false`

[hs_err_pid15072.log](https://github.com/MonetDBSolutions/MonetDBe-Java/files/6491465/hs_err_pid15072.log)

In the log I can see a java/io/FileNotFoundException related to [C:\jenkins\workspace\8-2-build-windows-amd64-cygwin\jdk8u291\1294\hotspot\src\share\vm\prims\jni.cpp, line 710]

It this something hardcoded in MonetDBe ? as I do not have Jenkins installed on my computer.

Thanks & regards,
Guillaume

**Comment by bernardom29** [comment] 2021-05-19 08:18
I believe this is only happening in the Windows version. I've tried to reproduce this crash on my mac laptop with SQL-Workbench/J, but wasn't able to. 
But when I tried to run SQL-Workbench/J on a Windows machine with the MonetDBe driver, I got a crash even when I tested the connection through the GUI (a crash was happening on the close() operation). 

I also got a similar message in the log file (this IO Exception on jni.cpp) but this is not something that's hardcoded in the Java layer of the MonetDBe-Java code. Perhaps it has to do with the C layer (this is a JNI application), but I'll have to do more experimentation to be sure.

So just to give you an update since I was working on other parts of this project, this week I'll take care of both of the issues you are experiencing. Hopefully you'll be able to use our driver normally once these are fixed.

Thanks again for trying out the MonetDBe-Java driver, I'll keep you posted on the progress of these two issues.

**Comment by njnes** [comment] 2021-05-21 11:26
Is it possible to create a example java program which has this problem without the SQL-Workbench environment?

**Comment by Guillaume789** [comment] 2021-05-25 07:12
Hi,
I spent lots of time trying to create a small java program to reproduce the crash, but unfortunately I cannot reproduce the crash inside the small program. Code is working fine inside the small program.
I will try again to reproduce the crash inside a small app...

**Comment by njnes** [comment] 2021-05-25 07:31
If its hard too reproduce with a simple application, it maybe related too multiple threads using a single connection to monetdbe. We are currently require each thread too have its own connection. But this is afcourse without me knowing much about the sql-workbench, i'm not sure it does use threads at all.

**Comment by Guillaume789** [comment] 2021-05-25 08:14
I manage to reproduce the crash in a simple app :)
Run below code and clik on the Button to execute the same code again.
You will get a crash at the second execution (once you click onthe button).

`package test;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.sql.DataSource;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

import org.apache.commons.dbcp2.BasicDataSource;
import org.apache.log4j.Logger;

public class Test4 {
	private static org.apache.log4j.Logger log = Logger.getLogger(Test4.class);
	
	/**
	 * Main
	 * @param args
	 * @throws Exception
	 */
    public static void main(String[] args) throws Exception {
        JFrame frame = new JFrame();
        JPanel panel = new JPanel();
        JButton runButton = new JButton("Run queries");
        panel.add(runButton);
        frame.setContentPane(panel);
        frame.setSize(200,100);
        frame.setVisible(true);
        
        runButton.addActionListener(e-> runQueries());
    	
    	runQueries();
    }
    
    public static void runQueries() {
    	try {
	    	BasicDataSource ds = new BasicDataSource();
	        ds.setDriverClassName("org.monetdb.monetdbe.MonetDriver");
	        ds.setUsername("monetdbe");
	        ds.setPassword("monetdbe");
	        ds.setUrl("jdbc:monetdb:memory:");
	        
	    	
	        String tableName = "cube_table_" + System.currentTimeMillis();
			log.info("Execute first query");
			String query0 = "CREATE TABLE "+tableName+" (\r\n"
					+ "	M_TRN_FMLY_S                             STRING,\r\n"
					+ "	M_TRN_GRP_S                              STRING,\r\n"
					+ "	M_TRN_TYPE_S                             STRING,\r\n"
					+ "	M_INSTRUMENT_S                           STRING,\r\n"
					+ "	M_TP_PFOLIO_S                            STRING,\r\n"
					+ "	M_NB_S                                   INTEGER,\r\n"
					+ "	M_RISK_SECT_S                            STRING,\r\n"
					+ "	M_PL_ABS_EUR_S                           DOUBLE,\r\n"
					+ "	M_MV_NF_EUR_S                            DOUBLE,\r\n"
					+ "	M_PC_NF_EUR_S                            DOUBLE,\r\n"
					+ "	M_PCR_NF_BK_S                            DOUBLE,\r\n"
					+ "	M_C_CUR_PL_S                             STRING,\r\n"
					+ "	M_CURRENCY_S                             STRING,\r\n"
					+ "	M_MIG_ID_S                               INTEGER,\r\n"
					+ "	M_TRN_FMLY_T                             STRING,\r\n"
					+ "	M_TRN_GRP_T                              STRING,\r\n"
					+ "	M_TRN_TYPE_T                             STRING,\r\n"
					+ "	M_INSTRUMENT_T                           STRING,\r\n"
					+ "	M_TP_PFOLIO_T                            STRING,\r\n"
					+ "	M_NB_T                                   INTEGER,\r\n"
					+ "	M_RISK_SECT_T                            STRING,\r\n"
					+ "	M_PL_ABS_EUR_T                           DOUBLE,\r\n"
					+ "	M_MV_NF_EUR_T                            DOUBLE,\r\n"
					+ "	M_PC_NF_EUR_T                            DOUBLE,\r\n"
					+ "	M_PCR_NF_BK_T                            DOUBLE,\r\n"
					+ "	M_C_CUR_PL_T                             STRING,\r\n"
					+ "	M_CURRENCY_T                             STRING,\r\n"
					+ "	M_MIG_ID_T                               INTEGER,\r\n"
					+ "	M_TRN_FMLY                               STRING,\r\n"
					+ "	M_TRN_GRP                                STRING,\r\n"
					+ "	M_TRN_TYPE                               STRING,\r\n"
					+ "	M_TP_PFOLIO                              STRING,\r\n"
					+ "	M_MIG_ID                                 INTEGER,\r\n"
					+ "	M_CURRENCY                               STRING,\r\n"
					+ "	M_INSTRUMENT                             STRING\r\n"
					+ ")";
			
			log.info("Execute first query\n"+query0);
			execute(ds, query0);
			
			log.info("Populate table...");
			String query = "insert into "+tableName+" (M_TRN_FMLY_S,M_TRN_GRP_S,M_TRN_TYPE_S,M_INSTRUMENT_S,M_TP_PFOLIO_S,M_NB_S,M_RISK_SECT_S,M_PL_ABS_EUR_S,M_MV_NF_EUR_S,M_PC_NF_EUR_S,M_PCR_NF_BK_S,M_C_CUR_PL_S,M_CURRENCY_S,M_MIG_ID_S,M_TRN_FMLY_T,M_TRN_GRP_T,M_TRN_TYPE_T,M_INSTRUMENT_T,M_TP_PFOLIO_T,M_NB_T,M_RISK_SECT_T,M_PL_ABS_EUR_T,M_MV_NF_EUR_T,M_PC_NF_EUR_T,M_PCR_NF_BK_T,M_C_CUR_PL_T,M_CURRENCY_T,M_MIG_ID_T) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
			Connection connection = ds.getConnection();
			PreparedStatement ps = connection.prepareStatement(query);
			
			for(int i=0;i<20;i++) {
				int index = 1;
				
				ps.setObject(index++, "CURR", java.sql.Types.VARCHAR);	// STRING,
				ps.setObject(index++, "FUT", java.sql.Types.VARCHAR);	// STRING,
				ps.setObject(index++, "FUT", java.sql.Types.VARCHAR);	// STRING,
				ps.setObject(index++, "FUT EURUSD", java.sql.Types.VARCHAR);	// STRING,
				ps.setObject(index++, "COM-METAL", java.sql.Types.VARCHAR);	// STRING,
				ps.setObject(index++, 31851519, java.sql.Types.INTEGER);	// INTEGER
				ps.setObject(index++, "EUR/USD", java.sql.Types.VARCHAR);	// STRING,
				ps.setObject(index++, -9286.0, java.sql.Types.DOUBLE);// DOUBLE,
				ps.setObject(index++, 0.0, java.sql.Types.DOUBLE);// DOUBLE,
				ps.setObject(index++, -9224.0, java.sql.Types.DOUBLE);// DOUBLE,
				ps.setObject(index++, 0.0, java.sql.Types.DOUBLE);// DOUBLE,
				ps.setObject(index++, "EUR", java.sql.Types.VARCHAR);	// STRING,
				ps.setObject(index++, "EUR", java.sql.Types.VARCHAR);	// STRING,
				ps.setObject(index++, 31851519, java.sql.Types.INTEGER);	// INTEGER
				
				ps.setNull(index++, java.sql.Types.VARCHAR);	// STRING,
				ps.setNull(index++, java.sql.Types.VARCHAR);	// STRING,
				ps.setNull(index++, java.sql.Types.VARCHAR);	// STRING,
				ps.setNull(index++, java.sql.Types.VARCHAR);	// STRING,
				ps.setNull(index++, java.sql.Types.VARCHAR);	// STRING,
				ps.setNull(index++, java.sql.Types.INTEGER);	// INTEGER
				ps.setNull(index++, java.sql.Types.VARCHAR);	// STRING,
				ps.setNull(index++, java.sql.Types.DOUBLE);// DOUBLE,
				ps.setNull(index++, java.sql.Types.DOUBLE);// DOUBLE,
				ps.setNull(index++, java.sql.Types.DOUBLE);// DOUBLE,
				ps.setNull(index++, java.sql.Types.DOUBLE);// DOUBLE,
				ps.setNull(index++, java.sql.Types.VARCHAR);	// STRING,
				ps.setNull(index++, java.sql.Types.VARCHAR);	// STRING,
				ps.setNull(index++, java.sql.Types.INTEGER);	// INTEGER				
				ps.addBatch();
				
				if((i % 2)==0) {
					log.debug(i);
					ps.execute();
					ps.clearBatch();
				}

				//DbUtils.execute(ds, "insert into cube_table_1620130268947 (M_TRN_FMLY_S,M_TRN_GRP_S,M_TRN_TYPE_S,M_INSTRUMENT_S,M_TP_PFOLIO_S,M_NB_S,M_RISK_SECT_S,M_PL_ABS_EUR_S,M_MV_NF_EUR_S,M_PC_NF_EUR_S,M_PCR_NF_BK_S,M_C_CUR_PL_S,M_CURRENCY_S,M_MIG_ID_S,M_TRN_FMLY_T,M_TRN_GRP_T,M_TRN_TYPE_T,M_INSTRUMENT_T,M_TP_PFOLIO_T,M_NB_T,M_RISK_SECT_T,M_PL_ABS_EUR_T,M_MV_NF_EUR_T,M_PC_NF_EUR_T,M_PCR_NF_BK_T,M_C_CUR_PL_T,M_CURRENCY_T,M_MIG_ID_T,M_TRN_FMLY,M_TRN_GRP,M_TRN_TYPE,M_TP_PFOLIO,M_MIG_ID,M_CURRENCY,M_INSTRUMENT) values (null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null)");
			}
			ps.execute();

			
			execute(ds, "alter table "+tableName+" add NB_RECORDS INT default 0");
			execute(ds, "alter table "+tableName+" add DIFF_PC_NF_EUR DOUBLE default 0");
			execute(ds, "alter table "+tableName+" add DIFF_PC_NF_EUR2 DOUBLE default 0");
			execute(ds, "alter table "+tableName+" add DIFF_MV_NF_EUR DOUBLE default 0");
			execute(ds, "alter table "+tableName+" add DIFF_PCR_NF_BK DOUBLE default 0");
			execute(ds, "alter table "+tableName+" add SUM_PL_ABS_EUR_T DOUBLE default 0");
			execute(ds, "alter table "+tableName+" add SUM_PL_ABS_EUR_S DOUBLE default 0");
			execute(ds, "alter table "+tableName+" add DIFF_PL_ABS_EUR DOUBLE default 0");
	
			String tableName2 = null;
			for(int i=0; i<1; i++) {
				tableName2 = tableName + "_" + i;
				log.info("Create table from table");
				execute(ds, "create table "+tableName2+" as select * from "+tableName+" where 1=1");
			}
	
			log.info("Terminated");
    	} catch(Exception e) {
    		e.printStackTrace();
    	}
	}

    /**
     * 
     * @param ds
     * @param query
     * @throws SQLException
     */
    private static void executeQuery(DataSource ds, String query) throws SQLException {
		Connection con = null;
		Statement stat = null;
		ResultSet rs = null;
		try {
			con  = ds.getConnection();
			stat = con.createStatement();
			rs   = stat.executeQuery(query);
			
			if(rs.next()) {
				log.info("First row is successfully retieved, let's quit the loop");
			}
		} finally {
			if(rs!=null) {
				rs.close();
			}
			if(stat!=null) {
				stat.close();
			}
			if(con!=null) {
				con.close();
			}
		}
    }
    
    private static boolean execute(DataSource ds, String query) throws SQLException {
		Connection con = null;
		Statement stat = null;
		try {
			con  = ds.getConnection();
			stat = con.createStatement();
			return stat.execute(query);
		} finally {
			if(stat!=null) {
				stat.close();
			}
			if(con!=null) {
				con.close();
			}
		}
    }

}
`

**Comment by Guillaume789** [comment] 2021-05-25 08:17
Not sure it is the same probel here...

**Comment by bernardom29** [comment] 2021-05-26 11:02
Today we found out that issue is related to multi-threading issues on the Windows version. Both the SQLWorkbench/J and the Swing GUIs use multi threads and share the connection between them, leading to these issues.

We'll be working on a fix as soon as possible.

**Comment by Guillaume789** [comment] 2021-05-26 13:41
Great, thanks for the information.
I am looking forward for the fix so I can continue to evaluate MonetDBe :)

**Comment by Guillaume789** [comment] 2021-06-17 20:37
Hello,
could you please provide feedback on your progress on the fix ?
Thanks, Guillaume

**Comment by bernardom29** [comment] 2021-06-25 14:24
Hello Guillaume!
Next week I'll be looking into this error, as we're still not sure why it's only happening on the windows version.
I'll let you know about the fix as soon as we release it.

Thanks for your continued interest in MonetDBe-Java

**Comment by Guillaume789** [comment] 2021-08-24 09:55
Hi Bernardo,
could you please provide feedback about your progress on the fix ?
Thanks & regards, Guillaume

**Comment by Guillaume789** [comment] 2021-09-13 06:29
Hi Bernardo,
I would be grateful if you could keep me updated with your progress.
Thanks, Guillaume

**Comment by bernardom29** [comment] 2022-01-05 16:44
Closing this issue, as it's related to multi-thread access to connections also mentioned in issue #8.
As stated on #8, the next MonetDBe-Java release will allow multiple threads to share a connection object.

**Closed as completed by bernardom29** 2022-01-05 16:44 UTC
